### ISSUE TITLE
It`s Usage?

### ISSUE THREAD

**Issue by Bright238** [virengajera/ngc#1]
Perfect work! Is it free to use on a live website? are there penalties of reusing their site homepage structure?

**Comment by virengajera** [comment]
You may have seen website with netflix,spotify etc. clone. It is just for learning purpose. You can use structure, layout or format of website according to your requirement in your own live projects But using other websites images and videos for generating income is prohibited.

**Comment by Bright238** [comment]
Well received! I like the idea that the structure looks really good. Good works!  From: Viren GajeraSent: Wednesday, January 5, 2022 10:47 AMTo: virengajera/ngcCc: Bright Kapamulomo Mafungautsi; AuthorSubject: Re: [virengajera/ngc] It`s Usage? (Issue #1) You may have seen website with netflix,spotify etc. clone. It is just for learning purpose. You can use structure, layout or format of website according to your requirement in your own live projects But using other websites images and videos for generating income is prohibited.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
